.PHONY: clean All

All:
	@echo "----------Building project:[ zadanie6 - Debug ]----------"
	@cd "zadanie6" && "$(MAKE)" -f  "zadanie6.mk"
clean:
	@echo "----------Cleaning project:[ zadanie6 - Debug ]----------"
	@cd "zadanie6" && "$(MAKE)" -f  "zadanie6.mk" clean
