.PHONY: clean All

All:
	@echo "----------Building project:[ project_2 - Debug ]----------"
	@cd "project_2" && "$(MAKE)" -f  "project_2.mk"
clean:
	@echo "----------Cleaning project:[ project_2 - Debug ]----------"
	@cd "project_2" && "$(MAKE)" -f  "project_2.mk" clean
