.PHONY: clean All

All:
	@echo "----------Building project:[ zadanie3 - Debug ]----------"
	@cd "zadanie3" && "$(MAKE)" -f  "zadanie3.mk"
clean:
	@echo "----------Cleaning project:[ zadanie3 - Debug ]----------"
	@cd "zadanie3" && "$(MAKE)" -f  "zadanie3.mk" clean
